project_name: 3D_CLIP
clip_embed_dim: 1280
clip_embed_version: OpenCLIP
vico_embed_dim: 500
model:
  name: PointBERT 
  in_channel: 6
  out_channel: ${clip_embed_dim}
  embedding_channel: 1024
  voxel_size: 0.02
  scaling: 4

training:
  use_openclip_optimizer_scheduler: False
  lr: 0.006
  lr_decay_step: 10000
  lr_decay_rate: 0.95
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  warmup: 10000
  max_epoch: 12
  log_freq: 1
  save_freq: 50
  lambda_img_contras: 1
  lambda_text_contras: 1
  use_image_proj: False 
  use_text_proj: False
  logit_scale_init: 14.28
  use_mask: False
  mask_threshold: 0.1
  freeze_layers: True

dataset:
  name: lvis_filter
  train_split: meta_data/split/train_all.json
  train_partial: -1
  num_points: 10000 
  num_workers: 6
  train_batch_size: 150
  # train_batch_size: 182
  test_batch_size: 47
  use_knn_negative_sample: False
  negative_sample_num: 1
  knn_path: meta_data/point_feat_knn.npy
  y_up: True
  normalize: True
  random_z_rotate: True
  use_color: True
  rgb_random_drop_prob: 0.5
  augment: True
  text_source: [text, caption, retrieval_text] 
  use_text_filtering: True
  use_prompt_engineering: True
  gpt4_filtering_path: meta_data/gpt4_filtering.json

objaverse_lvis:
  split: meta_data/split/lvis.json
  clip_feat_path: meta_data/lvis_cat_name_pt_feat.npy
  num_points: 10000 
  num_workers: 6
  # batch_size: 80
  batch_size: 150
  y_up: True
  normalize: True
  use_color: True
